docker_name: eduix/crowd
docker_tags:
  - "master"
builders:
  - docker
git:
  branch: master
  extensions:
    checkout_local_branch: true
clean_workspace: true

extra_jobs:
    - name: docker-crowd-daily
      git:
        branch: master
      triggers:
        github_push: false
        cron: "@daily"
    - name: docker-crowd-staging
      docker_tags:
        - "staging"
      git:
        branch: staging
    - name: docker-crowd-stable
      docker_tags:
        - "stable"
      git:
        branch: stable
