docker_name: eduix/crowd
builders:
  - script
script:
  - "echo \"Dummy job for starting branch specific ones\""
git:
  branches:
    - master
    - staging
    - stable
  extensions:
    checkout_local_branch: true
clean_workspace: true
downstream:
  - docker-crowd-master
  - docker-crowd-staging
  - docker-crowd-stable

extra_jobs:
    - name: docker-crowd-daily
      builders:
        - docker
      git:
        branch: master
      triggers:
        github_push: false
        cron: "@daily"
    - name: docker-crowd-master
      builders:
        - docker
      docker_tags:
        - "master"
      git:
        branch: master
    - name: docker-crowd-staging
      builders:
        - docker
      docker_tags:
        - "staging"
      git:
        branch: staging
    - name: docker-crowd-stable
      builders:
        - docker
      docker_tags:
        - "stable"
      git:
        branch: stable
