docker_name: eduix/crowd
builders:
  - docker
git:
  extensions:
    checkout_local_branch: true
clean_workspace: true

extra_jobs:
    - name: docker-crowd-daily
      git:
        branch: master
      triggers:
        github_push: false
        cron: @daily
    - name: docker-crowd-master
      docker_tags:
        - "master"
      git:
        branch: master
    - name: docker-crowd-staging
      docker_tags:
        - "staging"
      git:
        branch: staging
    - name: docker-crowd-stable
      docker_tags:
        - "stable"
      git:
        branch: stable
