docker_name: eduix/crowd
docker_tags:
    - "${GIT_LOCAL_BRANCH}"
git:
    branches:
        - master
        - stable
        - staging
    extensions:
        checkout_local_branch: true
clean_workspace: true
post_build_script:
  - "echo ${GIT_LOCAL_BRANCH}"
  - "echo ${scmVars.GIT_LOCAL_BRANCH}"
  - "echo ${env.GIT_LOCAL_BRANCH}"

extra_jobs:
    - name: docker-crowd-daily
      builders:
        - docker
      docker_name: eduix/crowd
      git:
        branch: master
        extensions:
            checkout_local_branch: true
      triggers:
        github_push: false
        cron: @daily
