docker_name: eduix/crowd
docker_tags:
    - "${GIT_LOCAL_BRANCH}"
docker_skip_tag_as_latest: true
git:
    branches:
        - master
        - stable
        - staging
    extensions:
        checkout_local_branch: true
clean_workspace: true

extra_jobs:
    - name: docker-crowd-daily
      builders:
        - docker
      docker_name: eduix/crowd
      docker_skip_tag_as_latest: false
      git:
        branch: master
        extensions:
            checkout_local_branch: true
      triggers:
        github_push: false
        cron: "@daily"
